# Generated by Django 4.2.5 on 2024-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('twilio_account_sid', models.CharField(max_length=100)),
                ('twilio_auth_token', models.CharField(max_length=100)),
                ('twilio_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
