# Generated by Django 4.2.5 on 2024-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='local_phone_number',
            field=models.CharField(default='+910000000000', max_length=20),
        ),
    ]
